using System;
using System.IO;
using FirebirdSql.Data.FirebirdClient;

namespace Home_Anywhere_D.SQLite.DataBase.DataBase_Access;

public class HawDesktopDb
{
	private static object locker = new object();

	private static bool initialized = false;

	private bool resetDb;

	public HawDesktopDb(string path = null)
	{
		Constants.CreatePath(path);
		Initialize();
	}

	private void CreateDatabase()
	{
		if (!File.Exists(Constants.DatabasePath))
		{
			FbConnection.CreateDatabase(Constants.ConnectionString);
			CreateTableSites();
			CreateTableCacheSites();
			CreateTableSettings();
		}
	}

	public void Initialize()
	{
		CreateDatabase();
		if (!initialized)
		{
			ResetDbIfNecessary();
			initialized = true;
		}
	}

	private void DropTable(string TitleTable)
	{
		using FbConnection fbConnection = new FbConnection(Constants.ConnectionString);
		using FbCommand fbCommand = fbConnection.CreateCommand();
		fbCommand.CommandText = "'drop table " + TitleTable + "';";
		fbConnection.Open();
		fbCommand.ExecuteScalar();
	}

	private void CreateTableSites()
	{
		using FbConnection fbConnection = new FbConnection(Constants.ConnectionString);
		using FbCommand fbCommand = fbConnection.CreateCommand();
		fbCommand.CommandText = "create table Sites \r\n                                            (\r\n                                                Id integer generated by default as identity primary key,\r\n                                                SiteID int not null,\r\n                                                ObjSite blob sub_type text \r\n                                            );";
		fbConnection.Open();
		fbCommand.ExecuteNonQuery();
	}

	private void CreateTableCacheSites()
	{
		using FbConnection fbConnection = new FbConnection(Constants.ConnectionString);
		using FbCommand fbCommand = fbConnection.CreateCommand();
		fbCommand.CommandText = "create table CacheSites \r\n                                            (\r\n                                                Id integer generated by default as identity primary key,\r\n                                                ObjectListInfo blob sub_type text \r\n                                            );";
		fbConnection.Open();
		fbCommand.ExecuteNonQuery();
	}

	private void CreateTableSettings()
	{
		using FbConnection fbConnection = new FbConnection(Constants.ConnectionString);
		using FbCommand fbCommand = fbConnection.CreateCommand();
		fbCommand.CommandText = "create table Settings \r\n                                            (\r\n                                                Id integer generated by default as identity primary key,\r\n                                                Language varchar(25),\r\n                                                LoginUsername varchar(30),\r\n                                                LoginPassword varchar(30),\r\n                                                RememberPassword char(1),\r\n                                                AutomaticLogin char(1),\r\n                                                WorkOffline char(1),\r\n                                                DefaultStartSiteID integer,\r\n                                                DefaultStartMapID integer,\r\n                                                StayActive char(1),\r\n                                                SleepAllowed char(1),\r\n                                                DefaultOrientation varchar(25),\r\n                                                LastVersionAck varchar(25),\r\n                                                Themes varchar(25),\r\n                                                Background varchar(25)\r\n                                            );";
		fbConnection.Open();
		fbCommand.ExecuteNonQuery();
	}

	private void ResetDbIfNecessary()
	{
	}

	public object SelectItemById(object item)
	{
		lock (locker)
		{
			object result = null;
			using (FbConnection fbConnection = new FbConnection(Constants.ConnectionString))
			{
				using FbCommand fbCommand = fbConnection.CreateCommand();
				if (item is Sites sites)
				{
					item = sites.SiteID;
				}
				if (item is int num)
				{
					fbCommand.CommandText = "select Id,SiteId,ObjSite from Sites where SiteId = @id;";
					fbCommand.Parameters.Add("id", num);
				}
				else if (item is CacheSites)
				{
					fbCommand.CommandText = "select first 1 Id,ObjectListInfo from CacheSites;";
				}
				else if (item is Settings)
				{
					fbCommand.CommandText = "select first 1 \r\n                                                    Id,\r\n                                                    LoginPassword, \r\n                                                    LoginUsername,\r\n                                                    Background,\r\n                                                    Language,\r\n                                                    Themes,\r\n                                                    AutomaticLogin,\r\n                                                    RememberPassword,\r\n                                                    SleepAllowed,\r\n                                                    DefaultStartMapID,\r\n                                                    DefaultOrientation,\r\n                                                    DefaultStartSiteID,\r\n                                                    LastVersionAck,\r\n                                                    StayActive,\r\n                                                    WorkOffline \r\n                                                    from Settings;";
				}
				fbConnection.Open();
				using FbDataReader fbDataReader = fbCommand.ExecuteReader();
				object[] values = new object[fbDataReader.FieldCount];
				while (fbDataReader.Read())
				{
					fbDataReader.GetValues(values);
					result = ReadResultDataBase(item, values);
				}
			}
			return result;
		}
	}

	public void UpdateOneItem(object item)
	{
		lock (locker)
		{
			using FbConnection fbConnection = new FbConnection(Constants.ConnectionString);
			using FbCommand fbCommand = fbConnection.CreateCommand();
			if (item is Sites sites)
			{
				fbCommand.CommandText = "update Sites set ObjSite = @objSite where SiteId = @SiteId;";
				fbCommand.Parameters.Add("objSite", sites.ObjSite);
				fbCommand.Parameters.Add("SiteID", sites.SiteID);
			}
			else if (item is CacheSites cacheSites)
			{
				if (cacheSites.Id == 0L)
				{
					cacheSites.Id = ((CacheSites)GetFirstItem(cacheSites)).Id;
				}
				fbCommand.CommandText = "update CacheSites set ObjectListInfo = @ObjectListInfo where Id = @id;";
				fbCommand.Parameters.Add("id", cacheSites.Id);
				fbCommand.Parameters.Add("ObjectListInfo", cacheSites.ObjectListInfo);
			}
			else if (item is Settings settings)
			{
				if (settings.Id == 0L)
				{
					settings.Id = ((Settings)GetFirstItem(settings)).Id;
				}
				fbCommand.CommandText = "update Settings \r\n                                                set LoginPassword = @password, \r\n                                                    LoginUsername = @username,\r\n                                                    Background = @Background,\r\n                                                    Language = @Language,\r\n                                                    Themes = @Themes,\r\n                                                    AutomaticLogin = @AutomaticLogin,\r\n                                                    RememberPassword = @RememberPassword,\r\n                                                    SleepAllowed = @SleepAllowed,\r\n                                                    DefaultStartMapID = @DefaultStartMapID,\r\n                                                    DefaultOrientation = @DefaultOrientation,\r\n                                                    DefaultStartSiteID = @DefaultStartSiteID,\r\n                                                    LastVersionAck = @LastVersionAck,\r\n                                                    StayActive = @StayActive,\r\n                                                    WorkOffline = @WorkOffline\r\n                                                    where Id = @id;";
				fbCommand.Parameters.Add("password", settings.LoginPassword);
				fbCommand.Parameters.Add("username", settings.LoginUsername);
				fbCommand.Parameters.Add("Background", settings.Background);
				fbCommand.Parameters.Add("Language", settings.Language);
				fbCommand.Parameters.Add("Themes", settings.Themes);
				fbCommand.Parameters.Add("AutomaticLogin", (!settings.AutomaticLogin) ? "0" : "1");
				fbCommand.Parameters.Add("RememberPassword", (!settings.RememberPassword) ? "0" : "1");
				fbCommand.Parameters.Add("SleepAllowed", (!settings.SleepAllowed) ? "0" : "1");
				fbCommand.Parameters.Add("DefaultStartMapID", settings.DefaultStartMapID);
				fbCommand.Parameters.Add("DefaultOrientation", settings.DefaultOrientation);
				fbCommand.Parameters.Add("DefaultStartSiteID", settings.DefaultStartSiteID);
				fbCommand.Parameters.Add("LastVersionAck", settings.LastVersionAck);
				fbCommand.Parameters.Add("StayActive", (!settings.StayActive) ? "0" : "1");
				fbCommand.Parameters.Add("WorkOffline", (!settings.WorkOffline) ? "0" : "1");
				fbCommand.Parameters.Add("id", settings.Id);
			}
			fbConnection.Open();
			fbCommand.ExecuteScalar();
		}
	}

	private object ReadResultDataBase(object item, object[] values)
	{
		object result = null;
		if (item is Sites || item is int)
		{
			result = new Sites
			{
				Id = Convert.ToInt64(values[0]),
				SiteID = Convert.ToInt32(values[1]),
				ObjSite = Convert.ToString(values[2])
			};
		}
		else if (item is CacheSites)
		{
			result = new CacheSites
			{
				Id = Convert.ToInt64(values[0]),
				ObjectListInfo = Convert.ToString(values[1])
			};
		}
		else if (item is Settings)
		{
			result = new Settings
			{
				Id = Convert.ToInt64(values[0]),
				LoginPassword = Convert.ToString(values[1]),
				LoginUsername = Convert.ToString(values[2]),
				Background = Convert.ToString(values[3]),
				Language = Convert.ToString(values[4]),
				Themes = Convert.ToString(values[5]),
				AutomaticLogin = (Convert.ToString(values[6]) == "1"),
				RememberPassword = (Convert.ToString(values[7]) == "1"),
				SleepAllowed = (Convert.ToString(values[8]) == "1"),
				DefaultStartMapID = Convert.ToInt32(values[9]),
				DefaultOrientation = Convert.ToString(values[10]),
				DefaultStartSiteID = Convert.ToInt32(values[11]),
				LastVersionAck = Convert.ToString(values[12]),
				StayActive = (Convert.ToString(values[13]) == "1"),
				WorkOffline = (Convert.ToString(values[14]) == "1")
			};
		}
		return result;
	}

	public object GetFirstItem(object item)
	{
		lock (locker)
		{
			object result = null;
			using (FbConnection fbConnection = new FbConnection(Constants.ConnectionString))
			{
				using FbCommand fbCommand = fbConnection.CreateCommand();
				if (item is Sites)
				{
					fbCommand.CommandText = "select first 1 Id,SiteId,ObjSite from Sites;";
				}
				else if (item is CacheSites)
				{
					fbCommand.CommandText = "select first 1 Id,ObjectListInfo from CacheSites;";
				}
				else if (item is Settings)
				{
					fbCommand.CommandText = "select first 1 \r\n                                                    Id,\r\n                                                    LoginPassword, \r\n                                                    LoginUsername,\r\n                                                    Background,\r\n                                                    Language,\r\n                                                    Themes,\r\n                                                    AutomaticLogin,\r\n                                                    RememberPassword,\r\n                                                    SleepAllowed,\r\n                                                    DefaultStartMapID,\r\n                                                    DefaultOrientation,\r\n                                                    DefaultStartSiteID,\r\n                                                    LastVersionAck,\r\n                                                    StayActive,\r\n                                                    WorkOffline \r\n                                                    from Settings;";
				}
				fbConnection.Open();
				using FbDataReader fbDataReader = fbCommand.ExecuteReader();
				object[] values = new object[fbDataReader.FieldCount];
				while (fbDataReader.Read())
				{
					fbDataReader.GetValues(values);
					result = ReadResultDataBase(item, values);
				}
			}
			return result;
		}
	}

	public long InsertOrUpdateItem<T>(T obj) where T : Entity
	{
		lock (locker)
		{
			if (SelectItemById(obj) != null)
			{
				UpdateOneItem(obj);
				return obj.Id;
			}
			InsertOneItem(obj);
			return obj.Id;
		}
	}

	public void InsertOneItem(object item)
	{
		lock (locker)
		{
			using FbConnection fbConnection = new FbConnection(Constants.ConnectionString);
			using FbCommand fbCommand = fbConnection.CreateCommand();
			if (item is Sites sites)
			{
				fbCommand.CommandText = "insert into Sites (ObjSite,SiteID) values (@ObjSite, @SiteID);";
				fbCommand.Parameters.Add("ObjSite", sites.ObjSite);
				fbCommand.Parameters.Add("SiteID", sites.SiteID);
			}
			else if (item is CacheSites cacheSites)
			{
				fbCommand.CommandText = "insert into CacheSites (ObjectListInfo) values (@ObjectListInfo);";
				fbCommand.Parameters.Add("ObjectListInfo", cacheSites.ObjectListInfo);
			}
			else if (item is Settings settings)
			{
				fbCommand.CommandText = "insert into Settings (LoginPassword,LoginUsername,Background,Language,Themes,AutomaticLogin,\r\n                                                        RememberPassword,SleepAllowed,DefaultStartMapID,DefaultOrientation,DefaultStartSiteID,\r\n                                                        LastVersionAck,StayActive,WorkOffline) values (\r\n                                                    @password, \r\n                                                    @username,\r\n                                                    @Background,\r\n                                                    @Language,\r\n                                                    @Themes,\r\n                                                    @AutomaticLogin,\r\n                                                    @RememberPassword,\r\n                                                    @SleepAllowed,\r\n                                                    @DefaultStartMapID,\r\n                                                    @DefaultOrientation,\r\n                                                    @DefaultStartSiteID,\r\n                                                    @LastVersionAck,\r\n                                                    @StayActive,\r\n                                                    @WorkOffline);";
				fbCommand.Parameters.Add("password", settings.LoginPassword);
				fbCommand.Parameters.Add("username", settings.LoginUsername);
				fbCommand.Parameters.Add("Background", settings.Background);
				fbCommand.Parameters.Add("Language", settings.Language);
				fbCommand.Parameters.Add("Themes", settings.Themes);
				fbCommand.Parameters.Add("AutomaticLogin", (!settings.AutomaticLogin) ? "0" : "1");
				fbCommand.Parameters.Add("RememberPassword", (!settings.RememberPassword) ? "0" : "1");
				fbCommand.Parameters.Add("SleepAllowed", (!settings.SleepAllowed) ? "0" : "1");
				fbCommand.Parameters.Add("DefaultStartMapID", settings.DefaultStartMapID);
				fbCommand.Parameters.Add("DefaultOrientation", settings.DefaultOrientation);
				fbCommand.Parameters.Add("DefaultStartSiteID", settings.DefaultStartSiteID);
				fbCommand.Parameters.Add("LastVersionAck", settings.LastVersionAck);
				fbCommand.Parameters.Add("StayActive", (!settings.StayActive) ? "0" : "1");
				fbCommand.Parameters.Add("WorkOffline", (!settings.WorkOffline) ? "0" : "1");
			}
			fbConnection.Open();
			fbCommand.ExecuteScalar();
		}
	}

	public int DeleteItem(object item)
	{
		lock (locker)
		{
			int result = 0;
			using (FbConnection fbConnection = new FbConnection(Constants.ConnectionString))
			{
				using FbCommand fbCommand = fbConnection.CreateCommand();
				if (item is int num)
				{
					fbCommand.CommandText = "delete from Sites where SiteID = @id;";
					fbCommand.Parameters.Add("id", num);
				}
				else if (item is CacheSites cacheSites)
				{
					fbCommand.CommandText = "delete from CacheSites where Id = @id;";
					fbCommand.Parameters.Add("id", cacheSites.Id);
				}
				else if (item is Settings settings)
				{
					fbCommand.CommandText = "delete from Settings where Id = @id";
					fbCommand.Parameters.Add("id", settings.Id);
				}
				fbConnection.Open();
				result = fbCommand.ExecuteNonQuery();
			}
			return result;
		}
	}

	public void DropCreateTable()
	{
		lock (locker)
		{
			DropDatabase();
			CreateDatabase();
		}
	}

	public void DropDatabase()
	{
		lock (locker)
		{
			if (File.Exists(Constants.DatabasePath))
			{
				FbConnection.DropDatabase(Constants.ConnectionString);
			}
		}
	}
}
